config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, only: [:session, :sign_in, :registration, :sign_out, :password]
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :events, only: [:index, :show] do
    resources :event_attendees, only: [:update]
    put '/join', to: 'posts#join', as: 'join'
    put '/leave', to: 'posts#leave', as: 'leave'
  end

  resources :users do
    resources :events
    get '/all_events', to: 'users#all_events', as: 'all_events'
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "events#index"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, foreign_key: "creator_id", class_name: "User"
  has_many :event_attendees, foreign_key: :attended_events_id
  has_many :attendees, through: :event_attendees, source: :attendee # return users that are attending

  validates :title, length: { minimum: 4 }, presence: true
  validates :description, length: { minimum: 4 }, presence: true
  validates :location, presence: true
  validates :start_date, presence: { message: "Date must be given" }
  validates :start_time, presence: { message: "Time must be given" }

  scope :past_events, -> { where("DATE(start_date) <= ?", Date.today) }
  scope :upcoming_events, -> { where("DATE(start_date) >= ?", Date.today)}
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @past_events = Event.past_events
    @upcoming_events = Event.upcoming_events
  end

  def show
    @event = Event.find(params[:id])
    @attending = @event.event_attendees&.exists?(attendee_id: current_user)
  end

  def new
    @event = Event.new
  end

  def edit
    @event = Event.find(params[:id])
    # @event is set by the before_action filter
  end

  def create
    puts "Event Information #{params[:user_id]}, #{params[:event]}"
    user = User.find(params[:user_id])
    @event = user.created_events.build(event_params)
   
    if @event.save
      # Add current user who created event to event attendees
      @event.event_attendees.create!(attendee_id: current_user.id) # raise ActiveRecord validation fail err if model is invalid, else create

      # Redirect user back to root page
      redirect_to root_path, notice: 'Event was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end 
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    # DELETE FROM table_name WHERE condition;
    EventAttendee.where("attended_events_id = ?", params[:event_id])
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully deleted.'
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :location, :start_date, :start_time)
  end
end

app/helpers/event_helper.rb
module EventHelper
end

app/views/events/edit.html.erb
<section class="flex flex-col p-4 mx-auto">
  <h2 class="text-center font-bold">Edit Event</h2>

  <%= form_with model: [:user, @event], class: "flex flex-col gap-4 p-8 shadow-lg rounded-md bg-white-05 mx-auto" do |form| %>

    <%= render partial: 'layouts/form_field', locals: { f: form, name: :title, field_type: :text, label: 'Title', value: 'Random anime event', placeholder: 'Title' } %>

    <%= render partial: 'layouts/form_field', locals: { f: form, name: :description, field_type: :text, label: 'Description', value: 'A anime event in Tokyo', placeholder: 'Description' } %>

    <%= render partial: 'layouts/form_field', locals: { f: form, name: :location, field_type: :text, label: 'Location', value: 'Gaming anime cafe', placeholder: 'Location' } %>

    <%= render partial: 'layouts/form_field', locals: { f: form, name: :start_date, field_type: :date, label: 'Date', value: @event.start_date, placeholder: '' } %>

    <%= render partial: 'layouts/form_field', locals: { f: form, name: :start_time, field_type: :time, label: 'Time', value: @event.start_time.strftime("%H:%M"), placeholder: '' } %>
    
    <%= form.submit "Save Changes", class: "bg-white-05 hover:bg-dark  text-white cursor-pointer font-bold p-2 rounded-md mt-4 block" %>

  <% end %>
</section>

app/views/events/index.html.erb
<div class="flex flex-col gap-4 mb-4">
  <section class="bg-white-05 p-2 md:p-8">
    <h1 class="text-2xl font-semibold mb-4 text-center md:text-left">Upcoming Events</h1>
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 justify-center sm:justify-start">
      <% @upcoming_events.each do |event| %>
        <%= link_to event_path(event) do %>
          <article class="bg-gradient-white border rounded">
            <h4 class="font-semibold text-center border-b p-4"><%= event.title %></h4>
            <p class="p-4"><%= event.description %></p><br>
            <div class="flex justify-evenly border-t text-center">
              <time class="p-2"><%= event.start_time.strftime("%I:%M %p") %></time>
              <span class="border"></span>
              <address class="p-2"><%= event.location %></address>
            </div>
          </article>
        <% end %>
      <% end %>
    </div>
  </section>

  <section class="bg-white-05 p-8">
    <h1 class="text-2xl font-semibold mb-4">Past Events</h1>
      <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 justify-center sm:justify-start">
        <% if @past_events %>
          <% @past_events.each do |event| %>
            <%= link_to event_path(event) do %>
              <article class="bg-gradient-white border rounded">
                <h4 class="font-semibold text-center border-b p-4"><%= event.title %></h4>
                <p class="p-4"><%= event.description %></p><br>
                <div class="flex justify-evenly border-t text-center">
                  <time class="p-2"><%= event.start_time.strftime("%I:%M %p") %></time>
                  <span class="border"></span>
                  <address class="p-2"><%= event.location %></address>
                </div>
              </article>
            <% end %>
          <% end %>
        <% end %>
    </div>
  </section>
  
</div>

app/views/events/new.html.erb
<section class="flex flex-col p-4 mx-auto">
  <h2 class="text-center font-bold">Create Event</h2>

  <%# user/6/event/new %>
  <%= form_with model: [:user, @event], class: "flex flex-col gap-4 p-8 shadow-lg rounded-md bg-white-05 mx-auto" do |form| %>

    <%= render partial: 'layouts/form_field', locals: { f: form, name: :title, field_type: :text, label: 'Title', value: 'Random anime event', placeholder: 'Title' } %>

    <%= render partial: 'layouts/form_field', locals: { f: form, name: :description, field_type: :text, label: 'Description', value: 'A anime event in Tokyo', placeholder: 'Description' } %>

    <%= render partial: 'layouts/form_field', locals: { f: form, name: :location, field_type: :text, label: 'Location', value: 'Gaming anime cafe', placeholder: 'Location' } %>

    <%= render partial: 'layouts/form_field', locals: { f: form, name: :start_date, field_type: :date, label: 'Date', value: '', placeholder: '' } %>

    <%= render partial: 'layouts/form_field', locals: { f: form, name: :start_time, field_type: :time, label: 'Time', value: '', placeholder: '' } %>

    <%= form.submit "Create Event", class: "bg-white-05 hover:bg-dark  text-white cursor-pointer font-bold p-2 rounded-md mt-4 block" %>

  <% end %>
</section>

app/views/events/show.html.erb
<article class="flex flex-col gap-4 md:w-1/2 mx-auto border p-4 rounded-md">
  <h1 class="font-semibold text-lg md:text-2xl text-center"> <%= @event.title %></h1>
  <% if @event.creator_id == current_user.id %>
    <%= link_to edit_user_event_path(current_user, @event), class: "absolute" do %>
      <button>
        <i class="material-icons outlined w-6 h-6">edit</i>
      </button>
    <% end %>
  <% end %>
  <div class="flex gap-4 justify-evenly flex-col text-center md:flex-row md:text-left items-center">
    <p>Hosted by <br><span class="font-semibold"><%= @event.creator.username %></span></p>
    <ul class="flex gap-4 items-center *:border *:rounded-md *:p-2">
      <%= render partial: "layouts/event_attendees", locals: { event: @event } %>
    </ul>
  </div>

  <p class="text-pretty my-4"><%= @event.description %></p>

  <ul class="flex items-center justify-evenly *:border *:rounded-md *:p-2 gap-4 *:text-sm md:*:text-md">
    <li>
      <address><%= @event.location %></address>
    </li>
    <li>
      <time><%= @event.start_time.strftime("%I:%M %p") %></time>
    </li>
  </ul>
  
  <div class="mx-auto">
    <% if @attending %>
      <%= button_to "Leave this event", event_event_attendee_path(@event), method: :put, class: "bg-white-05 hover:bg-dark p-2 rounded-md mx-auto my-4" %>
    <% else %>
      <%= button_to "Join this event", event_event_attendee_path(@event), method: :put, class: "bg-white-05 hover:bg-dark p-2 rounded-md mx-auto my-4" %>
    <% end %>
  </div>

</article>