config/routes.rb
Rails.application.routes.draw do
  # devise_for :users, only: [:session, :sign_in, :registration, :sign_out, :password]
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :events, only: [:index, :show] do
    resources :event_attendees, only: [:update]
    put '/join', to: 'posts#join', as: 'join'
    put '/leave', to: 'posts#leave', as: 'leave'
  end

  resources :users do
    resources :events
    get '/all_events', to: 'users#all_events', as: 'all_events'
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "events#index"
end

app/views/layouts/_error_message.html.erb
<% if objects.errors.any? %>
  <div class="bg-red text-white p-4 rounded-md" id="error-message">
    <h3>Unable to save due to the followings:</h3>
    <ol class="list-decimal p-4">
      <% objects.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ol>
  </div>
  <script>
    setTimeout(() => {
      document.getElementById("error-message").remove();
    }, 5000);
  </script>
<% end %>

app/views/layouts/_event_attendees.html.erb
<button class="modal-open">
  <li>Attending: <span><%= @event.attendees.length %></span></li>
</button>

<!--Modal-->
<div class="modal opacity-0 pointer-events-none fixed w-full h-full top-0 left-0 flex items-center justify-center">
  <div class="modal-overlay absolute w-full h-full bg-black opacity-70"></div>

  <div class="modal-container fixed w-full h-full z-50 overflow-y-auto ">
    
  <div class="modal-close absolute top-0 right-0 cursor-pointer flex flex-col items-center mt-4 mr-4 text-black text-sm z-50">
      <svg class="fill-current text-black" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18">
        <path d="M14.53 4.53l-1.06-1.06L9 7.94 4.53 3.47 3.47 4.53 7.94 9l-4.47 4.47 1.06 1.06L9 10.06l4.47 4.47 1.06-1.06L10.06 9z"></path>
      </svg>
      (Esc)
    </div>

    <!-- Add margin if you want to see grey behind the modal-->
    <div class="modal-content container mx-auto h-auto text-left p-4">
    
    <!--Title-->
      <div class="flex justify-between items-center pb-2">
        <p class="text-2xl font-bold">Full Screen Modal!</p>
      </div>

      <!--Body-->
      <p>Modal content can go here</p>

      <ul>
        <% event.attendees.each do |attendee| %>
          <li>
            <%= attendee.username %>
          </li>
        <% end %>
      </ul>
      
      <!--Footer-->
      <div class="flex justify-end pt-2">
        <button class="px-4 bg-transparent p-3 rounded-lg text-indigo-500 hover:bg-gray-100 hover:text-indigo-400 mr-2">Action</button>
        <button class="modal-close px-4 bg-indigo-500 p-3 rounded-lg text-white hover:bg-indigo-400">Close</button>
      </div>

    </div>
  </div>
</div>


<script>
  var openmodal = document.querySelectorAll('.modal-open')
  for (var i = 0; i < openmodal.length; i++) {
    openmodal[i].addEventListener('click', function(event){
  	event.preventDefault()
  	toggleModal()
    })
  }
  
  const overlay = document.querySelector('.modal-overlay')
  overlay.addEventListener('click', toggleModal)
  
  var closemodal = document.querySelectorAll('.modal-close')
  for (var i = 0; i < closemodal.length; i++) {
    closemodal[i].addEventListener('click', toggleModal)
  }
  
  document.onkeydown = function(evt) {
    evt = evt || window.event
    var isEscape = false
    if ("key" in evt) {
  	isEscape = (evt.key === "Escape" || evt.key === "Esc")
    } else {
  	isEscape = (evt.keyCode === 27)
    }
    if (isEscape && document.body.classList.contains('modal-active')) {
  	toggleModal()
    }
  };
  
  
  function toggleModal () {
    const body = document.querySelector('body')
    const modal = document.querySelector('.modal')
    modal.classList.toggle('opacity-0')
    modal.classList.toggle('pointer-events-none')
    body.classList.toggle('modal-active')
  }
  
   
</script>

app/views/layouts/_form_field.html.erb
<div class="flex flex-col">
  <%= f.label "#{name}:", "#{label}:" %>

  <% if field_type == :date %>
    <%= f.date_field "#{name}", value: "#{value}", placeholder: "#{placeholder}", class: "form-control w-full text-black #{'is-invalid' if f.object.errors["#{name}"].present?}" %>

  <% elsif field_type == :time %>
    <%= f.time_field "#{name}", value: "#{value}", placeholder: "#{placeholder}", class: "form-control w-full text-black #{'is-invalid' if f.object.errors["#{name}"].present?}" %>
  <% else %>

    <%= f.text_field "#{name}", value: "#{value}", placeholder: "#{placeholder}", class: "form-control w-full text-black #{'is-invalid' if f.object.errors["#{name}"].present?}" %>
  <% end %>

  <% if f.object.errors["#{name}"].present? %>
    <div class="text-red text-sm">
      <%= f.object.errors["#{name}"].first %>
    </div>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<nav class="w-full text-white bg-bluePurple p-6 fixed top-0 left-0">
  <ul class="flex gap-4 items-center w-full">

    <%= link_to root_path do %>
      <li class="flex items-center gap-4">
        <%= image_tag asset_path("icon.png"), class: "rounded-full w-12 h-12" %>
        <h3 class="font-bold">Animetoon</h3>
      </li>
    <% end %>

    <ul class="ml-auto">
      <% if user_signed_in? %>
        <%= render 'layouts/navcontent'%>
        <% else %>
        <li>
          <%= link_to "Login", new_user_session_path %> |
          <%= link_to "Sign Up", new_user_registration_path %>
        </li>
      <% end %>
    </ul>
  </ul>
</nav>

app/views/layouts/_navcontent.html.erb
<label class="popup cursor-pointer">
  <input type="checkbox">
  <div class="burger" tabindex="0">
    <span></span>
    <span></span>
    <span></span>
  </div>
  <nav class="popup-window">
    <ul>
      <li class="text-center">
        <%= link_to edit_user_registration_path do %>
          <span><%= current_user.username %></span>
        <% end %>
      </li>
      <hr>
      <li>
        <%= link_to user_all_events_path(current_user) do %>
          <button>
            <i class="material-icons outlined w-6 h-6">events</i>
            <span>Attended Events</span>
          </button>
        <% end %>
      </li>
      <li>
        <%= link_to new_user_event_path(user_id: current_user.id) do %>
          <button>
            <i class="material-icons outlined w-6 h-6">events</i>
            <span>Create Event</span>
          </button>
        <% end %>
      </li>
      <hr>
      <li>
        <%= button_to destroy_user_session_path, method: :delete do %>
          <i class="material-icons outlined p-0">logout</i>
          <span>Logout</span>
        <% end %>
      </li>
    </ul>
  </nav>
</label>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Animetoon</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if !devise_controller? || (devise_controller? && action_name != "new" && action_name != "create") %>
      <%= render "layouts/nav" %>
    <% end %>
<%#     <main class="container mx-auto mt-28 px-5 flex h-screen"> %>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>